### ISSUE TITLE
CORS support

### ISSUE THREAD

**Issue by kirstin51D** [51Degrees/pipeline-java#18]
We've identified that we need to modify the javascript and json elements to return CORS elements.

**Comment by justadreamer** [comment]
a patch to the examples has been implemented: https://github.com/51Degrees/pipeline-java/pull/43 however it seems the intention is to implement this on the level of the library.  it is impossible to do on the javascript/json elements as these are not serving headers, but on the middle-ware level packages it should be possible.  we need to think on a way how to parameterize what origins should be allowed.

**Comment by justadreamer** [comment]
this should be done as part of #54

**Comment by justadreamer** [comment]
@kirstin51D if you feel need to reopen - please do
