### ISSUE TITLE
429 Error Response from 51Degrees cloud service when no Referer or Origin header has been set.

### ISSUE THREAD

**Issue by Joseph51D** [51Degrees/pipeline-java#2]
The error message: "Referer or Origin header in the request not set, please contact us at support@51degrees.com to find out more."

This error occurs after a number of requests where traffic has been marked as suspicious because it doesn't look like it's coming from real web browsers. The reason for this is because there is no Referer or Origin header present in the request, so the 51Degrees cloud service isn't able to recognise this traffic as legitimate live traffic.

Currently there is no way to set a default Referer header in the cloud Pipeline or `CloudRequestEngine` builders. In .NET you can work around this by setting default headers on the `HTTPClient` you pass into the `CloudRequestEngineBuilder`.

The workaround in the Java API will depend on the implementation but generally it is to add the Referer header to the evidence:

```java
try (FlowData flowData = pipeline.createFlowData()) {
    flowData
        .addEvidence("header.Referer", "domain.invalid")
        .process();
}
```

**Comment by Steve51D** [comment]
This will be resolved in the next release of pipeline-java, scheduled for Wed 18th August.

**Comment by Joseph51D** [comment]
The setCloudRequestOrigin parameter is now accepted by CloudRequestEngineBuilder, as well as related builders such as DeviceDetectionCloudPipelineBuilder.

As with all element/pipeline builder parameters, this can be specified in code:

```java
CloudRequestEngine engine = new CloudRequestEngineBuilder(loggerFactory)
    .setResourceKey(resourceKey)
    .setCloudRequestOrigin("51degrees.com")
    .build();
``` 

```java
Pipeline pipeline = new DeviceDetectionPipelineBuilder(loggerFactory)
    .useCloud(resourceKey)
    .setCloudRequestOrigin("51degrees.com")
    .build();
```
    
or configuration:

```xml
<PipelineOptions>
    <Elements>
        <Element>
            <BuildParameters>
                <ResourceKey>xxx</ResourceKey>
                <CloudRequestOrigin>51degrees.com</CloudRequestOrigin>
            </BuildParameters>
            <BuilderName>CloudRequestEngine</BuilderName>
        </Element>
        <Element>
            <BuilderName>DeviceDetectionCloudEngine</BuilderName>
        </Element>
    </Elements>
</PipelineOptions>
```
